config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/bookings/my_bookings', to: 'bookings#my_bookings', as: :my_bookings
  get '/bookings/:id/accepted', to: 'bookings#accepted', as: :accept_booking
  get '/bookings/:id/declined', to: 'bookings#declined', as: :decline_booking
  get '/bookings/:id', to: 'bookings#show', as: :show_booking
  get '/bikes/my_bikes', to: 'bikes#my_bikes', as: :my_bikes
  get '/bookings/:id/edit', to: 'bookings#edit', as: :edit_booking
  patch '/bookings/:id', to: 'bookings#update', as: :booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bikes do
    post '/bookings', to: 'bookings#create'
  end
  resources :bookings, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :delete_all
  validates :brand, :category, :location, :price_per_day, :description, presence: true
  validates :description, length: { minimum: 10 }
  validates :price_per_day, numericality: { only_integer: true }
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bike
  validates :booking_end, :booking_start, :total_price, presence: true

  enum status: {
    Pending: 0,
    Accepted: 1,
    Declined: 2,
    Canceled: 3
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :bikes, dependent: :delete_all
  has_many :bookings, dependent: :delete_all
  has_many :owner_bookings, through: :bikes, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :find_bike, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "\
      location ILIKE :query \
      OR brand ILIKE :query \
      OR category ILIKE :query \
      "
      @bikes = Bike.where(sql_query, query: "%#{params[:query]}%")
    else
      @bikes = Bike.all
    end
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: { bike: bike }),
        image_url: helpers.asset_url("person-biking-solid.svg")
      }
    end
  end

  def show
    @booking = Booking.new
    @markers = @bike.geocode.map do {
                 lat: @bike.latitude,
                 lng: @bike.longitude,
                 # info_window: render_to_string(partial: "info_window", locals: { bike: @bike }),
                 image_url: helpers.asset_url("person-biking-solid.svg")
              }
    end
  end
  # Sharon : method New

  def new
    if user_signed_in?
      @bike = Bike.new
    else
      redirect_to root_path
    end
  end

  # Sharon : method Create
  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    if @bike.save
      redirect_to my_bikes_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @bike.update(bike_params)
      redirect_to @bike, notice: 'Your updated bike is ready.'
    else
      render :edit
    end
  end

  def destroy
    @bike.destroy if @bike.user == current_user

    redirect_to bikes_path
  end

  def my_bikes
    if user_signed_in?
      @bikes = Bike.where(user: current_user)
    else
      redirect_to root_path
    end
  end

  private

  def find_bike
    @bike = Bike.find(params[:id])
  end

  def bike_params
    # added photo as a parameter.
    params.require(:bike).permit(:brand, :category, :location, :price_per_day, :description, :photo)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy]
  before_action :find_bike, only: [:create, :new]

  def my_bookings
    if user_signed_in?
      @bookings = Booking.where(user: current_user)
      @bikes_bookings = current_user.owner_bookings
    else
      redirect_to root_path
    end
  end

  def show
    redirect_to root_path unless user_signed_in? && @booking.user == current_user
  end

  def new
    @bookings = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    @booking.user = current_user
    @booking.total_price = (@booking.booking_end - @booking.booking_start) * @bike.price_per_day

    if @booking.save
      redirect_to my_bookings_path(@booking)
    else
      render 'bikes/show'
    end
  end

  def accepted
    @booking = Booking.find(params[:id])
    @booking.Accepted! if @booking.bike.user == current_user

    redirect_to my_bookings_path
  end

  def declined
    @booking = Booking.find(params[:id])
    @booking.Declined! if @booking.bike.user == current_user

    redirect_to my_bookings_path
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to my_bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy

    redirect_to my_bookings_path
  end

  private

  def find_bike
    @bike = Bike.find(params[:bike_id])
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:booking_start, :booking_end)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h2><%= bike.brand %></h2>
<p><%= bike.location %></p>

app/views/bikes/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-4">
        <h3 class="text-center mb-4 mt-5">Edit your Bike Listing</h3>

        <div class="col-12 mb-6">
          <%= simple_form_for @bike do |f| %>
            <%= f.input :brand %>
            <%= f.input :location,
                        wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } },
                        input_html: { data: { geocoder_target: "location" }, class: "d-none" } %>
            <%= f.input :price_per_day %>
            <%= f.input :category %>
            <%= f.input :description %>
            <div class="d-grid gap-2">
              <%= f.submit class: "btn btn-info mb-5 mt-3 rounded" %>
            </div>
          <% end %>

        </div>
    </div>
  </div>
</div>

app/views/bikes/my_bikes.html.erb
<div class="container d-flex justify-content-between p-0">
  <h1 class='mx-3 my-3 fw-bolder'> My Bikes:</h1>
  <div class='button mx-3 my-3'>
      <%= link_to 'Create a Bike', new_bike_path, class: 'btn btn-info', class: 'btn btn-info w-100 shadow-sm' %>
  </div>
</div>

<ul class="p-0">
    <% @bikes.each do |bike| %>
      <li class="container mt-3"  style="list-style: none;">
          <div class="mb-3 shadow">
            <div class="d-flex justify-content-between">
              <img class="position-fixed shadow" height=100%;>
                <% if bike.photo.attached? %>
                  <%= cl_image_tag bike.photo.key, width: 350, crop: :fill %>
                <% end %>
              <div class="p-1 my-3">
                <h2 class="text-center mb-2 mt-3"> <%= link_to bike.brand, bike_path(bike), class: "text-decoration-none text-dark text-uppercase fw-bolder"%></h2>
                <hr>
                <p class="mt-2"><strong>Description:</strong> <%= bike.description %></p>
                <p><%= bike.location %></p>

              </div>
              <div class ="d-flex flex-column align-items-center p-4 justify-content-around" >
                <%= link_to 'Details', bike_path(bike), class: "btn btn-info w-100 shadow-sm" %>

                <% if bike.user == current_user %>
                  <%= link_to "Edit", edit_bike_path(bike), class: 'btn btn-info w-100 shadow-sm' %>
                <% end %>

                <% if bike.user == current_user %>
                  <%= link_to "Delete", bike_path(bike),
                    method: :delete,
                    data: { confirm: "Are you sure you want to delete this bike?" },
                    class: 'ms-3 text-danger',  class: 'btn btn-danger w-100 shadow-sm'  %>
                <% end %>
              </div>
            </div>
          </div>
      </li>
    <% end %>

</ul>

app/views/bikes/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-4">
      <%# <form action="" class="row"> %>
        <h3 class="text-center mb-4 mt-5">Create a New Bike Listing</h3>

        <div class="col-12 mb-6">
          <%= simple_form_for @bike do |f| %>
            <%= f.input :photo, as: :file %>
            <%= f.input :brand, placeholder: 'Brand' %>
            <%= f.input :location,
                        wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } },
                        input_html: { data: { geocoder_target: "location" }, class: "d-none" } %>
            <%= f.input :price_per_day, placeholder: 'Price per day' %>
            <%= f.input :category, placeholder: 'Category' %>
            <%= f.input :description, placeholder: 'Description' %>
            <div class="d-grid gap-2">
              <%= f.submit class: 'btn btn-info mb-5 mt-3 rounded'%>
            </div>
          <% end %>

        </div>
    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<div class = "container mt-5">


<div class='container'>
  <div class='row'>
    <div id="bike-info" class='col-6 card d-flex flex-column justify-content-between"'>
      <% if @bike.photo.attached? %>
        <%= cl_image_tag @bike.photo.key, class:"col-12", height: 250, crop: :fill %>
      <% end %>
      <div>
        <h2 class = "text-center">
          <%= @bike.brand %>
        </h2>

        <h3 class = "text-center">
          Daily Price: $<%= @bike.price_per_day %>
        </h3>

        <h3 class = "text-center">
          <%= @bike.location %>
        </h3>

        <p class = "text-center">
          <%= @bike.description %>
        </p>

        <div class='d-flex justify-content-center'>
          <% if @bike.user == current_user %>
            <%= link_to "Edit", edit_bike_path(@bike), class: "btn btn-info", style: "min-width: 100px;" %>
          <% end %>


          <% if @bike.user == current_user %>
            <%= link_to "Delete", bike_path(@bike),
            data: { confirm: "Are you sure you want to delete this bike?" },
            method: :delete,
            class: 'ms-3 btn btn-danger',
            style: "min-width: 100px;" %>
          <% end %>
        </div>
      </div>
    </div>


    <div  id="map-mapbox" class='col-6' style="width: 50%; height: 500px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

  <div data-controller="bookings" class="form-wrapper">
    <% unless @bike.user == current_user %>
      <h3 class="text-begin mb-4 mt-5">Book this Bike:</h3>
        <%= simple_form_for([@bike, @booking], wrapper: :inline_form,
                            html: { class: "row row-cols-lg-auto g-4 align-items-center justify-content-center" },
                            wrapper_mappings: { boolean: :inline_boolean }) do |f| %>
          <%= f.input :booking_start, as: :string, required: false, input_html: {class: "datepicker col-12"} %>
          <%= f.input :booking_end, as: :string, required: false, input_html: {class: "datepicker col-12"} %>
            <%= f.button :submit, "Book", class: "btn btn-info rounded col-12" %>
        <% end %>
      <% end %>
  </div>

app/views/bookings/edit.html.erb
<div class="container">
  <div data-controller="bookings" class="form-wrapper">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8 col-lg-4">
          <h3 class="text-center mb-4 mt-5">Change Booking Dates:</h3>

          <div class="col-12 mb-6">
            <%= simple_form_for @booking do |f| %>
              <%= f.input :booking_start, as: :string, required: false, input_html: {class: "datepicker"} %>
              <%= f.input :booking_end, as: :string, required: false, input_html: {class: "datepicker"} %>
              <div class="d-grid gap-2">
                <%= f.button :submit, "Book", class: "btn btn-info mb-5 mt-3 rounded" %>
              </div>
            <% end %>

          </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="container">
  <h2 class="text-center my-4">My Bookings:</h2>
</div>

<% if @bookings %>
  <ul class="p-0">
    <% @bookings.each do |booking| %>
      <li class="container py-2"  style="list-style: none;">
        <div class="mb-3 shadow">
          <div class="d-flex justify-content-between">
            <img class="position-fixed shadow" height=100%;>
            <% if booking.bike.photo.attached? %>
              <%= cl_image_tag booking.bike.photo.key, width: 190, crop: :fill %>
            <% end %>
            <div class="p-1 my-3">
              <h2 class="text-center text-dark text-uppercase mb-4 mt-3"><%= booking.bike.brand %></h2>
              <hr>
              <p class="my-5"><strong>Description:</strong> <%= booking.bike.description %></p>
              <p class="mt-5">
                from:
                <%= booking.booking_start %>
                - to:
                <%= booking.booking_end %>
                -- Status: <%= booking.status %>
              </p>
            </div>
            <div class ="d-flex flex-column align-items-center p-4 justify-content-around" >
              <h2><%= booking.bike.location %></h2>
              <h2>
                <i class="fa-solid fa-dollar-sign my-4">
                  <%= booking.total_price %>
                </i>
              </h2>
              <%= link_to 'Details', booking_path(booking), class: "btn btn-info w-100 shadow-sm" %>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>


<hr>
<div class="container">
  <h2 class="text-center">My Bikes Booked:</h2>
</div>

<% if @bikes_bookings %>
  <ul class="p-0">
    <% @bikes_bookings.each do |booking| %>
      <li class="container py-2"  style="list-style: none;">
        <div class="mb-3 shadow">
          <div class="d-flex justify-content-between">
            <img class="position-fixed shadow" height=100%;>
            <% if booking.bike.photo.attached? %>
              <%= cl_image_tag booking.bike.photo.key, width: 240, crop: :fill %>
            <% end %>
            <div class="p-1 my-3">
              <h2 class="text-center mb-2 mt-3 text-dark text-uppercase"><%= booking.bike.brand %></h2>
              <hr>
              <p class="my-5"><strong>Description:</strong> <%= booking.bike.description %></p>
              <p class="mt-5">
                from:
                <%= booking.booking_start %>
                - to:
                <%= booking.booking_end %>
                -- Booker: <%= booking.user.email %>
              </p>
            </div>
            <div class ="d-flex flex-column align-items-center p-4 justify-content-around" >
              <h2>
                <i class="fa-solid fa-dollar-sign my-4">
                  <%= booking.total_price %>
                </i>
              </h2>
              <h2><%= booking.status %></h2>
              <% if booking.status == 'Pending' %>
                <%= link_to 'Accept', accept_booking_path(booking), class: "btn btn-info w-100 shadow-sm mb-2" %>
                <%= link_to 'Decline', decline_booking_path(booking), class: "btn btn-danger w-100 shadow-sm" %>
              <% end %>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/bookings/show.html.erb
<h1>Details on <%= @booking.bike.brand %> - <%= @booking.bike.category %></h1>

<div class="card text-center">
  <div class="card-header">
    STATUS : <%= @booking.status %>
  </div>
  <div class="card-body">
    <h5 class="card-title">DATES : <%= @booking.booking_start %> - <%= @booking.booking_end %></h5>
    <p class="card-text"><%= @booking.bike.brand %></p>
    <p class="card-text"><%= @booking.bike.category %></p>
    <p class="card-text"><%= @booking.bike.description %></p>
    <p class="card-text">Total price : <%= @booking.total_price %> $</p>
    <%#=Not sure of the path %>
    <%= link_to 'Edit', edit_booking_path(@booking), class:"btn btn-info" %>
    <%= link_to "Delete", booking_path(@booking), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" }  %>
    <%= link_to "My Bookings", my_bookings_path, class: "btn btn-info" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cycleasy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/1b7f7cd915.js" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>


  </head>

  <body class="bg-light">
    <div id="page-container">
      <div id="content-wrap">
        <%= render 'shared/navbar' %>
          <%= yield %>
      </div>
      <footer id="footer">
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
        <div class="footer-copyright">
          PCSJ - Cycleasy 2022
        </div>
      </footer>
    </div>

    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1549216963-72c1712c1196?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=869&q=80);">
  <div class="container">
    <h1><strong>CYCLEASY</strong></h1>
    <p>The easiest way to rent a bike!</p>
    <%= link_to "Browse Bikes", bikes_path, class:"btn btn-info" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo_cycleasy.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "All Bikes", bikes_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "My Bikes", my_bikes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", my_bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://ca.slack-edge.com/T02NE0241-U039ZBN5J11-gc43c9b2b007-512" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>